import { PreloadedKnowledge } from './types';

export const STAGE_WIDTH = 800;
export const STAGE_HEIGHT = 450;

export const cameraHeightOptions = ['ground-level soul gaze', 'eye-level witness', 'elevated guardian', 'angelic drift'];
export const cameraAngleOptions = ['true-eye, honest', 'steep reverence', 'whispered low', 'Dutch slip'];
export const lightingMoodOptions = [
  'chiaroscuro confession',
  'soft volumetric prayer',
  'neon fever dream',
  'moonlit echo',
  'burnt tungsten reminiscence'
];
export const colorHarmonyOptions = ['complementary pulse', 'analogous drift', 'triadic bloom', 'monochrome trance', 'split-complementary tension'];
export const easingOptions = ['linear', 'ease-in', 'ease-out', 'ease-in-out'];
export const movementTypes = ['static contemplation', 'slow dolly-in', 'crane ascent', 'handheld tremor', 'steadicam drift', 'orbital pan'];
export const easingMap: Record<string, any> = {
  linear: 'linear',
  'ease-in': 'easeIn',
  'ease-out': 'easeOut',
  'ease-in-out': 'easeInOut'
};

export const questions = [
    { id: 'scriptText', step: 0, category: 'Prelude (Optional)', question: 'Optional: share your script fragment or scene description', placeholder: 'Drop in a fragment if you want Dreamer to adapt pacing and continuity from the page.', type: 'script', randomOptions: ['He edits reels of his past while rain combs the window.','She waits in a station bathed in crimson departures.','They argue in whispers beneath the crashing surf.'] },
    { id: 'sceneCore', step: 1, category: 'Scene Core & Emotion', question: 'Describe your scene core — who is there, what is happening, what emotion drives it.', placeholder: 'e.g., A man edits reels of his past in a dark room while rain falls outside.', type: 'text', randomOptions: ['A woman reading farewell letters in a candlelit attic as thunder stirs the glass.','Two siblings share a cigarette on a motel balcony overlooking neon emptiness.'] },
    { id: 'emotion', step: 1, category: 'Scene Core & Emotion', question: 'What mood defines this scene?', placeholder: 'melancholic, nostalgic, ethereal...', type: 'select', options: ['melancholic','nostalgic','ethereal','tragic beauty','mythic surrealism','serene chaos','hopeful decay','electric longing'] },
    { id: 'numberOfShots', step: 2, category: 'Shot System', question: 'How many shots should the sequence contain?', placeholder: 'e.g., 5 — establishing, emotional reaction, revelation, contrast, payoff', type: 'text', randomOptions: ['3', '5', '7'] },
    { id: 'cameraType', step: 2, category: 'Shot System', question: 'Select your camera system:', type: 'select', options: ['Arri Alexa 65', 'Red Monstro 8K', 'Sony Venice 2', 'Phantom Flex 4K', 'IMAX', 'analog Bolex H16'] },
    { id: 'shotTypes', step: 2, category: 'Shot System', question: 'Which shot types shape your sequence?', placeholder: 'wide, close-up, POV, dolly-in...', type: 'text', randomOptions: ['wide atmospheric, dolly-in confession, close-up tremor','aerial drift, tracking pursuit, over-the-shoulder reveal'] },
    { id: 'focalLength', step: 2, category: 'Shot System', question: 'Choose focal length:', type: 'select', options: ['10mm ultra-wide','24mm immersive','35mm cinematic','50mm human-eye','85mm intimate','135mm compressed'] },
    { id: 'depthOfField', step: 2, category: 'Shot System', question: 'Set the depth of field:', type: 'select', options: ['f/1.4 dreamy shallow', 'f/2.8 cinematic shallow', 'f/5.6 balanced', 'f/11 deep focus'] },
    { id: 'framing', step: 3, category: 'Framing & Visual Psychology', question: 'What composition defines the scene?', type: 'select', options: ['rule of thirds','symmetrical','negative space','frame-in-frame','golden ratio','off-center','leading lines','Dutch angle'] },
    { id: 'mainCharacterBlocking', step: 4, category: 'Character Choreography', question: 'Where is your protagonist in the frame?', placeholder: 'centered in soft light, edge isolation...', type: 'text', randomOptions: ['centered, leaning into the glow of a single practical.','edge isolation, half in shadow, half in reflected neon.'] },
    { id: 'secondaryCharacterBlocking', step: 4, category: 'Character Choreography', question: 'Where are other presences or energies?', placeholder: 'midground, overlapping movement...', type: 'text', randomOptions: ['midground silhouettes pacing like echoes.','background figures drifting past frosted glass.'] },
    { id: 'antagonistBlocking', step: 4, category: 'Character Choreography', question: 'How is opposition or tension represented?', placeholder: 'off-frame shadow pressing in...', type: 'text', randomOptions: ['off-frame shadow creeping along the wall.','rear silhouette looming behind a gauze curtain.'] },
    { id: 'lightingStyle', step: 5, category: 'Lighting & Atmosphere', question: 'Choose lighting mood:', type: 'select', options: ['chiaroscuro contrast','golden hour glow','moonlit reflection','tungsten haze','silhouette rim','fluorescent spill'] },
    { id: 'lightingDetails', step: 5, category: 'Lighting & Atmosphere', question: 'Specify technical feel:', placeholder: '4:1 ratio, halation glow, volumetric fog...', type: 'text', randomOptions: ['4:1 ratio with halation glow kissing the highlights.','volumetric fog, twin practicals, underexposed edges.'] },
    { id: 'atmosphere', step: 5, category: 'Lighting & Atmosphere', question: 'Add atmosphere:', placeholder: 'rain, fog, dust motes...', type: 'text', randomOptions: ['slow rain trembling against the panes.','floating dust motes illuminated by projector light.'] },
    { id: 'filmStock', step: 6, category: 'Film Stock & Color', question: 'Select film stock:', type: 'select', options: ['Kodak Vision3 500T 5219','Fuji Eterna','Ilford HP5 B&W','Technicolor 3-strip','Polaroid pastel dream'] },
    { id: 'filmEmulation', step: 6, category: 'Film Stock & Color', question: 'Texture level:', placeholder: '35mm authentic grain, halation bloom...', type: 'text', randomOptions: ['35mm authentic grain with gentle halation bloom.','medium ISO texture, preserved luminance, subtle gate weave.'] },
    { id: 'colorGrading', step: 6, category: 'Film Stock & Color', question: 'Color grade vibe:', type: 'select', options: ['mutated pastel','teal-orange tension','noir desaturation','golden warmth','painterly tone','infrared surreal'] },
    { id: 'colorPalette', step: 6, category: 'Film Stock & Color', question: 'Define color palette (hex codes) or let Dreamer adapt harmonically.', placeholder: 'background #1A1F2B, midtone #4A6C6F, highlight #F2C27E', type: 'text', randomOptions: ['background #1A1F2B, midtone #305A63, highlight #F0C179','background #120E1A, midtone #3B2F58, highlight #E6B4F6'] },
    { id: 'storyBeat', step: 7, category: 'Story Voice & Poetic Link', question: 'Add a short poetic line summarizing the emotional core.', placeholder: 'He edits by rhythm now, not reason.', type: 'text', randomOptions: ['He edits by rhythm now, not reason.','Her laughter flickers against the wall like a ghost of light.'] },
    { id: 'visualToneKeywords', step: 7, category: 'Story Voice & Poetic Link', question: 'Describe your visual identity:', placeholder: 'cinematic, painterly, liminal, emotional realism...', type: 'text', randomOptions: ['cinematic, painterly, liminal, emotional realism.','mythic surrealism, tactile, whisper-soft focus.'] },
    { id: 'continuityMode', step: 8, category: 'Continuity & Output Structure', question: 'Select continuity type:', type: 'select', options: ['tight continuity', 'loose evolution', 'poetic drift', 'rhythm-based motif'] },
    { id: 'seedLinking', step: 8, category: 'Continuity & Output Structure', question: 'How should seeds link from shot to shot?', type: 'select', options: ['use previous seeds', 'mutate previous seeds', 'ignore previous seeds'] },
    { id: 'resolution', step: 8, category: 'Continuity & Output Structure', question: 'Choose output fidelity:', type: 'select', options: ['4K render','filmic softness','volumetric depth','photoreal detail','painterly grain','analog imperfection'] },
    { id: 'outputType', step: 8, category: 'Continuity & Output Structure', question: 'Select format:', type: 'select', options: ['still image','cinematic frame','storyboard','concept art','matte painting','AI film still','AI Video Scene'] },
    { id: 'visualCompositionGuide', step: 9, category: 'Visual Design · Composition', question: 'Composition guide: where will your subjects breathe inside the frame?', type: 'select', options: ['center-frame devotion with symmetrical weight','rule-of-thirds drift, negative space whispering pressure','foreground silhouette with background revelation'] },
    { id: 'visualCameraSetup', step: 9, category: 'Visual Design · Composition', question: 'Camera setup: height, angle, and emotional distance?', type: 'select', options: ['eye-level witness, respectful distance','low-angle reverence, hero towering','high-angle confession, subject humbled'] },
    { id: 'visualLightingSetup', step: 10, category: 'Visual Design · Lighting', question: 'Lighting setup: how do key, fill, and backlights converse?', type: 'text', placeholder: 'Key 80% warm, Fill 40% cool...', randomOptions: ['Key 80% warm amber, Fill 35% moonlit blue, Back 60% neutral rim','Key 70% tungsten amber, Fill 30% green spill, Back 55% magenta halo'] },
    { id: 'visualLightingMood', step: 10, category: 'Visual Design · Lighting', question: 'Lighting mood: what emotion do the photons sculpt?', type: 'select', options: lightingMoodOptions },
    { id: 'visualColorPalette', step: 11, category: 'Visual Design · Color', question: 'Color palette: dominant hues, warmth versus cool, saturation?', type: 'text', placeholder: 'Dominant teal shadows, warm peach highlights...', randomOptions: ['Dominant teal shadows, warm peach highlights, 65% saturation','Crimson mids, emerald shadows, 45% saturation'] },
    { id: 'visualColorHarmony', step: 11, category: 'Visual Design · Color', question: 'Color harmony: which relationship guides your palette?', type: 'select', options: colorHarmonyOptions },
    { id: 'visualCameraMovement', step: 12, category: 'Visual Design · Motion', question: 'Camera movement: which motion carries the emotional tide?', type: 'select', options: movementTypes },
    { id: 'visualFocusMotion', step: 12, category: 'Visual Design · Motion', question: 'Focus motion: do we pull focus, breathe the zoom, or hold still?', type: 'select', options: ['no movement, razor still focus','focus pull from background to foreground','breathing zoom drift inward'] },
];

export const preloadedKnowledgeBase: PreloadedKnowledge[] = [
    {
      id: 'preloaded-1',
      name: 'Story Structure & Narrative Frameworks',
      content: `A story structure... Generally story follow some structure, there are various way to do it and one of them is Harmon story circle 1. You A character in their zone of comfort 2. Need wants something 3. Go! so they enter an unfamiliar situation 4. Struggle to which they have to adapt 5. Find in order to get what they want 6. Suffer yet they have to make a sacrifice 7. Return before they return to their familiar situation 8. Change having changed fundamentally. The Hero’s journey- story structure: THE ORDINARY WORLD. THE CALL TO ADVENTURE. REFUSAL OF THE QUEST. ACCEPTING THE CALL: ENTERING THE UNKNOWN. SUPERNATURAL AID. TALISMAN: ALLIES/HELPERS. TESTS & THE SUPREME ORDEAL. REWARD AND THE JOURNEY HOME. MASTER OF TWO WORLDS/ RESTORING THE WORLD.`,
      extractedKnowledge: { themes: ['redemption', 'transformation', 'return'], visualStyles: ['epic journey', 'cyclical narrative', 'three-act structure'], characters: ['mentor', 'herald', 'trickster'], techniques: ['inciting incident', 'dark night of the soul', 'climax', 'The Hero\'s Journey'] }
    },
    {
      id: 'preloaded-2',
      name: 'Advanced Character Development',
      content: `A compelling protagonist is defined by their journey. Past: A character's past should not be a mere footnote, but a formative influence that actively shapes their present motivations, fears, and strengths. These past experiences, whether traumatic or triumphant, should ripple through their current actions and decisions. Present: The immediate challenges a character faces are the engine of your story. These conflicts can be multifaceted: External Conflict, Internal Conflict, Interpersonal Conflict. Escalate the Stakes: The inciting incident should not be a universal event with equal impact on all. For your protagonist, the stakes must be inherently higher, more personal, and potentially devastating if they fail. Pushing Boundaries: Don't hesitate to thrust your character out of their comfort zone from the outset. Chained Reactions: Avoid easily resolvable conflicts. A truly engaging narrative thrives on a chain reaction of escalating problems. ARCHETYPES APPEARING IN THE HERO’S JOURNEY: HEROES, SHADOWS, MENTORS, HERALD, THRESHOLD GUARDIANS, SHAPESHIFTERS, TRICKSTERS, ALLIES, WOMAN AS TEMPTRESS. Character arc, positive change- character might believe in a lie, goes through confrontation and then reaches acceptance. Flat character ARC- character already believe in truth, truth is tested… he wins and keep the truth. Negative character arc- character might loose positive character trait, keep believing in a lie and take decision on the basis of it resulting into negative outcome. Save the Cat is a screenwriting concept where the protagonist does something early in the story to make them relatable or likable.`,
      extractedKnowledge: { themes: ['internal conflict', 'fatal flaw', 'growth vs. stagnation'], visualStyles: ['character-driven scenes', 'subjective POV', 'emotional close-ups'], characters: ['reformer', 'loyalist', 'challenger', 'hero', 'shadow', 'mentor'], techniques: ['ghost/wound', 'active vs. passive choice', 'character introductions', 'positive arc', 'flat arc', 'negative arc', 'save the cat'] }
    },
    {
      id: 'preloaded-3',
      name: 'Cinematography & Camera Techniques',
      content: 'Notes. Write or draw the use of lightning, sound, camera movement, aspects ratio, character movment. Framing, composition. Angle. Transition between two frame Depth of field, by crossing out ,0ut of focus stuff. 180° rule, an imaginary line between two characters drawn… we are not supposed to cross the line… makes it look like both characters are in same place. Cut on action, switch between full to medium shot in a single scene. Show weather, time of the day. Movement of character should give sense of what they would do... Audience should be able to anticipate.',
      extractedKnowledge: { themes: ['power dynamics', 'isolation', 'freedom', 'anticipation'], visualStyles: ['dolly zoom', 'long take', 'dutch angle', 'weather effects'], characters: [], techniques: ['180-degree rule', 'rule of thirds', 'lead room', 'motivated character movement', 'cut on action', 'depth of field'] }
    },
    {
      id: 'preloaded-4',
      name: 'Professional Lighting',
      content: `Understanding Lighting: Shaping Mood and Form. Three-Point Lighting System: Key Light, Fill Light, Backlight (Rim/Separation Light), Kicker Light, Motivated Lighting. Lighting Techniques & Styles: Rembrandt Lighting, Loop Lighting, Split Lighting, Butterfly (Paramount) Lighting, Clamshell Lighting, Silhouette Lighting, Low-Key Lighting, High-Key Lighting. Light Softness & Distance: Larger light source = Softer shadows. Smaller light source = Harsher shadows. Closer light = Softer shadows. Farther light = Harsher shadows. Modifiers to Soften Light: Softbox, Umbrella, Bounce (Reflector), Diffusion Gel or Scrim. Additional Cinematic Rules: Shoot from the Dark Side. Broad vs. Short Lighting.`,
      extractedKnowledge: { themes: ['mystery', 'spirituality', 'interrogation', 'beauty', 'glamour'], visualStyles: ['chiaroscuro', 'high-key', 'low-key', 'silhouette', 'soft light', 'hard light'], characters: ['femme fatale', 'hardboiled detective'], techniques: ['three-point lighting', 'motivated lighting', 'practical lights', 'Butterfly lighting', 'Clamshell lighting', 'Rembrandt Lighting', 'Loop Lighting', 'Split Lighting', 'Short vs Broad lighting', 'light modifiers (softbox, umbrella)'] }
    },
    {
      id: 'preloaded-5',
      name: 'Dialogue & Subtext',
      content: `The Art of Scene Writing: Subtext and Transformation. A well-crafted scene is more than just dialogue and action. Subtext: Inject subtext into your scenes. Hint at deeper meanings, unspoken emotions, or underlying tensions without explicitly stating them. A subtle gesture, a loaded silence, or an object's placement can speak volumes. Scene Arc: Every scene should have a mini-arc, transforming the character or the situation. Initial Goal, Initial Action, Obstacle/Reaction, Transformation/New Correlation. Driving Questions: "Who wants what from whom?", "What happens if they don't get it?", "Why now?". Subtext is the unsaid—what’s felt, implied, or hinted at but never directly spoken. It turns simple dialogue into rich, multi-layered interactions. Enter Late, Exit Early: A storytelling principle used to keep scenes tight and impactful.`,
      extractedKnowledge: { themes: ['deception', 'unspoken truth', 'power struggle'], visualStyles: ['over-the-shoulder shots', 'reaction shots', 'two-shots'], characters: [], techniques: ['subtext', 'exposition as ammunition', 'pacing and rhythm', 'scene arc', 'enter late, exit early'] }
    },
    {
      id: 'preloaded-6',
      name: 'Conflict & Stakes',
      content: `The real unity of opposites is one in which compromise is impossible." - to write conflict dialogue becomes powerful when characters have hidden agendas. The Unity of Opposites is the theory that great conflict comes from characters with opposing needs, values, or goals, who are locked together in a situation where neither can back down or walk away. Inciting incidents, story generation methods, logline structure. Frame of movie writing process: LOGLINE, SYNOPSIS, PLOT DEVELOPMENT.`,
      extractedKnowledge: { themes: ['man vs. self', 'man vs. society', 'man vs. nature'], visualStyles: ['rising tension', 'montage sequences', 'cross-cutting'], characters: ['antagonist', 'protagonist'], techniques: ['ticking clock', 'raising the stakes', 'reversal of fortune', 'unity of opposites', 'logline', 'synopsis'] }
    },
    {
        id: 'preloaded-7',
        name: 'Opening Scene Hooks',
        content: 'Opening scene- flashback, flash forward, mid-story (in media res), newsreel, the setting, crime, direct addressing, tragedy, a day in life. These can even be called hooks… Establishing shot: wide shots that are shows in the starts of scene. Another hook, could be a tripod shot (static) or a chasing sequence.',
        extractedKnowledge: { themes: ['memory', 'destiny', 'chaos', 'exposition', 'atmosphere', 'justice', 'intimacy', 'loss', 'normalcy'], visualStyles: ['non-linear', 'in media res', 'documentary', 'world-building', 'noir', 'fourth-wall break', 'dramatic'], characters: [], techniques: ['flashback', 'flash-forward', 'cold open', 'montage', 'establishing shot', 'direct address'] }
    },
    {
        id: 'preloaded-8',
        name: 'Advanced Screenwriting Principles',
        content: 'Screenplay convention: Keep it visual and in present tense. Write V.O for voice over, add cut to or back to for scene change. Montage start and montage end. Dialogues in the centre. Linear vs Non-Linear Storylines. Exposition: The method of conveying backstory or world-building. Good exposition feels natural and is integrated into the story. Techniques include: Dialogues, Photographs/Documents, Flashbacks, Environment/Props.',
        extractedKnowledge: { themes: ['hidden meaning', 'efficiency', 'narrative structure', 'backstory'], visualStyles: ['layered performance', 'tight pacing', 'chronological vs fragmented', 'naturalistic reveals'], characters: [], techniques: ['subtextual dialogue', 'scene transitions', 'non-linear storytelling', 'show don\'t tell', 'V.O.', 'montage formatting'] }
    },
    {
        id: 'preloaded-9',
        name: 'Narrative Development & Visual Execution',
        content: `This guide explores key elements of narrative development and visual execution, offering insights for screenwriters, directors, and storytellers alike. Character Development: Past, Present, and Conflict. A compelling protagonist is defined by their journey. Their past should actively shape their present motivations, fears, and strengths. The immediate challenges a character faces are the engine of your story, including external, internal, and interpersonal conflicts. Escalate the stakes to be personal and devastating for the protagonist. Push characters out of their comfort zone from the outset. A truly engaging narrative thrives on a chain reaction of escalating problems. The Art of Scene Writing: Subtext and Transformation. Inject subtext into your scenes, hinting at deeper meanings without explicitly stating them. Every scene should have a mini-arc that transforms the character or the situation. Structure a powerful scene by asking: "Who wants what from whom?", "What happens if they don't get it?", and "Why now?". Storyboarding: Visualizing the Narrative. Storyboarding is the visual blueprint, detailing lighting, sound, camera movement, aspect ratio, character movement, framing, composition, angle, transition between frames, and depth of field. Screenplay Conventions: Adhere to standard conventions for clarity and professionalism. Describe what can be seen and heard in the present tense. Use standard formatting for Voice Over (V.O.), scene transitions ("CUT TO:"), and montages. Story Structure: Harmon Story Circle. A simplified variation of the "Hero's Journey": 1. You (Comfort Zone), 2. Need (Desire), 3. Go! (Unfamiliar Situation), 4. Struggle (Adaptation), 5. Find (Achievement), 6. Suffer (Sacrifice), 7. Return (Familiar Situation), 8. Change (Transformation).`,
        extractedKnowledge: { themes: ['Conflict', 'Transformation', 'Sacrifice', 'Personal Stakes', 'Duality', 'Introspection', 'Mystery'], visualStyles: ['Chiaroscuro', 'High Contrast', 'Motivated Lighting', 'Visual Blueprinting', 'Dynamic Composition'], characters: ['Protagonist', 'Antagonist'], techniques: ['Subtext','Scene Arc','Inciting Incident','Escalating Stakes','Three-Point Lighting','Key Light','Fill Light','Backlight','Kicker Light', 'Rembrandt Lighting','Loop Lighting','Split Lighting','Depth of Field','Screenplay Formatting (V.O., Montage)','Harmon Story Circle'] }
    },
    {
        id: 'preloaded-10',
        name: 'Advanced Character, World & Story Dynamics',
        content: `Deep character psychology including conscious/unconscious forces (people, institutions vs. myths, culture, memory). Core external conflict of the world. Thematic Suture (Unity of Opposites): a core theme confronted through two opposing values, with an antagonist who mirrors or distorts the protagonist. Dialogue & Contrast: a character's first line reflects their false belief; subvert stereotypes and reveal core contradictions. Plot & Arc (From Fracture to Catharsis): an external conflict drives the plot while an internal contradiction drives the character, from an inciting crisis through a midpoint twist to a final transformation or failure. Relatability & Transcendence: find the ordinary/human in a character to make their life feel mythic, creating an audience bond. Symbolic Objects & Motivated Cuts: use objects to represent inner truths and motivate visual cuts (match cut, smash cut). Enneagram x Want/Need x Power Dynamics grid for character reactions. 3 KEYFRAME STORY SEED STRUCTURE: a 7-step process from setup to final expression. CHARACTER–WORLD DYNAMIC GRID: maps conscious/unconscious characters pursuing need/want against a supporting/opposing world. Character Internal States: Outer Mask, Private Self, Core Wound/Truth. Social Reaction Shifts: "We are who we think they think we are."`,
        extractedKnowledge: { themes: ['Duality (Conscious/Unconscious)', 'Conflict (Internal/External)', 'Transformation', 'Subversion', 'Power Dynamics', 'Want vs. Need', 'Fate vs. Choice', 'Relatability', 'Transcendence', 'Audience Connection'], visualStyles: ['Symbolic Motifs', 'Motivated Cuts (Match, Smash, Echo)', 'Visual Echoes', 'Character-centric Framing', 'Thematic Color Palettes'], characters: ['Enneagram Archetypes', 'Characters defined by internal states (Mask, Private Self, Core Wound)', 'Antagonists as Mirrors', 'Subverted Stereotypes', 'Characters with hidden agendas'], techniques: ['Enneagram Story Arcs', 'Keyframe Story Structure', 'Character-World Dynamic Grid', 'Unity of Opposites', 'Inciting Crisis', 'Midpoint Twist', 'Symbolic Objects', 'First Line Character Reveal', 'Contradictory Behavior', 'Fracture to Catharsis Arc', 'Want/Need Grid', 'Social Mirror (Character Shifts)'] }
    },
    {
        id: 'preloaded-11',
        name: 'Advanced Story & Narrative Theory',
        content: `The Hero's Journey story structure (THE ORDINARY WORLD, THE CALL TO ADVENTURE, REFUSAL, ENTERING THE UNKNOWN, SUPERNATURAL AID, ALLIES, TESTS & THE SUPREME ORDEAL, REWARD, THE JOURNEY HOME, MASTER OF TWO WORLDS). Classic character archetypes (HEROES, SHADOWS, MENTORS, HERALD, THRESHOLD GUARDIANS, SHAPESHIFTERS, TRICKSTERS, ALLIES). Various character arcs (positive change, flat, negative). Techniques for story generation ("What If", dreams, forced connections, personal experience). Professional screenplay formatting for LOGLINE and SYNOPSIS.`,
        extractedKnowledge: { themes: ["The Call to Adventure", "Transformation", "Moral Choice", "Growth", "Stagnation", "Corruption"], visualStyles: ["Epic Journey", "Mythic Structure", "Character-driven Pacing"], characters: ["Hero", "Shadow", "Mentor", "Herald", "Threshold Guardian", "Shapeshifter", "Trickster", "Ally"], techniques: ["The Hero's Journey", "Positive Change Arc", "Flat Character Arc", "Negative Character Arc", "Logline", "Synopsis", "Save the Cat", "What If Scenarios"] }
    },
    {
        id: 'preloaded-12',
        name: 'Advanced Cinematic Techniques',
        content: `Advanced camera movements (Slow Push-In for tension/intimacy, Creep-Out for isolation, The Moment for emotional peaks). Paranoid framing (wide frame, distant subject, slow zooms). Distraction techniques to mislead audience focus. Walter Murch's 'In the Blink of an Eye' editing theory: editing is emotional, not just technical. The "Rule of Six" for a good cut: 1. Emotion (51%), 2. Story (23%), 3. Rhythm (10%), 4. Eye-trace (7%), 5. 2D Plane (5%), 6. 3D Space (4%). Great editing is invisible. Fundamental principles of exposure and camera settings (Aperture, Shutter Speed, ISO).`,
        extractedKnowledge: { themes: ["Tension", "Intimacy", "Isolation", "Paranoia", "Powerlessness", "Emotional Continuity"], visualStyles: ["Invisible Editing", "Rhythmic Cutting", "Paranoid Thriller", "Subjective Camera"], characters: [], techniques: ["Slow Push-In", "Creep-Out", "The Moment (Emotional Peak)", "Distraction (Misdirection)", "Paranoid Zoom", "Walter Murch's Rule of Six", "Exposure Triangle (Aperture, Shutter, ISO)", "Cut on Action"] }
    }
  ];